// Generated by gencpp from file turtle_controller/TurtlesSrv.msg
// DO NOT EDIT!


#ifndef TURTLE_CONTROLLER_MESSAGE_TURTLESSRV_H
#define TURTLE_CONTROLLER_MESSAGE_TURTLESSRV_H

#include <ros/service_traits.h>


#include <turtle_controller/TurtlesSrvRequest.h>
#include <turtle_controller/TurtlesSrvResponse.h>


namespace turtle_controller
{

struct TurtlesSrv
{

typedef TurtlesSrvRequest Request;
typedef TurtlesSrvResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct TurtlesSrv
} // namespace turtle_controller


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::turtle_controller::TurtlesSrv > {
  static const char* value()
  {
    return "7bcae82d9c56d7e11c9ed0787b32d9b5";
  }

  static const char* value(const ::turtle_controller::TurtlesSrv&) { return value(); }
};

template<>
struct DataType< ::turtle_controller::TurtlesSrv > {
  static const char* value()
  {
    return "turtle_controller/TurtlesSrv";
  }

  static const char* value(const ::turtle_controller::TurtlesSrv&) { return value(); }
};


// service_traits::MD5Sum< ::turtle_controller::TurtlesSrvRequest> should match
// service_traits::MD5Sum< ::turtle_controller::TurtlesSrv >
template<>
struct MD5Sum< ::turtle_controller::TurtlesSrvRequest>
{
  static const char* value()
  {
    return MD5Sum< ::turtle_controller::TurtlesSrv >::value();
  }
  static const char* value(const ::turtle_controller::TurtlesSrvRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::turtle_controller::TurtlesSrvRequest> should match
// service_traits::DataType< ::turtle_controller::TurtlesSrv >
template<>
struct DataType< ::turtle_controller::TurtlesSrvRequest>
{
  static const char* value()
  {
    return DataType< ::turtle_controller::TurtlesSrv >::value();
  }
  static const char* value(const ::turtle_controller::TurtlesSrvRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::turtle_controller::TurtlesSrvResponse> should match
// service_traits::MD5Sum< ::turtle_controller::TurtlesSrv >
template<>
struct MD5Sum< ::turtle_controller::TurtlesSrvResponse>
{
  static const char* value()
  {
    return MD5Sum< ::turtle_controller::TurtlesSrv >::value();
  }
  static const char* value(const ::turtle_controller::TurtlesSrvResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::turtle_controller::TurtlesSrvResponse> should match
// service_traits::DataType< ::turtle_controller::TurtlesSrv >
template<>
struct DataType< ::turtle_controller::TurtlesSrvResponse>
{
  static const char* value()
  {
    return DataType< ::turtle_controller::TurtlesSrv >::value();
  }
  static const char* value(const ::turtle_controller::TurtlesSrvResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // TURTLE_CONTROLLER_MESSAGE_TURTLESSRV_H
