// Generated by gencpp from file turtle_controller/TurtlesSrvRequest.msg
// DO NOT EDIT!


#ifndef TURTLE_CONTROLLER_MESSAGE_TURTLESSRVREQUEST_H
#define TURTLE_CONTROLLER_MESSAGE_TURTLESSRVREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace turtle_controller
{
template <class ContainerAllocator>
struct TurtlesSrvRequest_
{
  typedef TurtlesSrvRequest_<ContainerAllocator> Type;

  TurtlesSrvRequest_()
    : name()  {
    }
  TurtlesSrvRequest_(const ContainerAllocator& _alloc)
    : name(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _name_type;
  _name_type name;





  typedef boost::shared_ptr< ::turtle_controller::TurtlesSrvRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::turtle_controller::TurtlesSrvRequest_<ContainerAllocator> const> ConstPtr;

}; // struct TurtlesSrvRequest_

typedef ::turtle_controller::TurtlesSrvRequest_<std::allocator<void> > TurtlesSrvRequest;

typedef boost::shared_ptr< ::turtle_controller::TurtlesSrvRequest > TurtlesSrvRequestPtr;
typedef boost::shared_ptr< ::turtle_controller::TurtlesSrvRequest const> TurtlesSrvRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::turtle_controller::TurtlesSrvRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::turtle_controller::TurtlesSrvRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::turtle_controller::TurtlesSrvRequest_<ContainerAllocator1> & lhs, const ::turtle_controller::TurtlesSrvRequest_<ContainerAllocator2> & rhs)
{
  return lhs.name == rhs.name;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::turtle_controller::TurtlesSrvRequest_<ContainerAllocator1> & lhs, const ::turtle_controller::TurtlesSrvRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace turtle_controller

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::turtle_controller::TurtlesSrvRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::turtle_controller::TurtlesSrvRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::turtle_controller::TurtlesSrvRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::turtle_controller::TurtlesSrvRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::turtle_controller::TurtlesSrvRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::turtle_controller::TurtlesSrvRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::turtle_controller::TurtlesSrvRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "c1f3d28f1b044c871e6eff2e9fc3c667";
  }

  static const char* value(const ::turtle_controller::TurtlesSrvRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xc1f3d28f1b044c87ULL;
  static const uint64_t static_value2 = 0x1e6eff2e9fc3c667ULL;
};

template<class ContainerAllocator>
struct DataType< ::turtle_controller::TurtlesSrvRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "turtle_controller/TurtlesSrvRequest";
  }

  static const char* value(const ::turtle_controller::TurtlesSrvRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::turtle_controller::TurtlesSrvRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string name\n"
;
  }

  static const char* value(const ::turtle_controller::TurtlesSrvRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::turtle_controller::TurtlesSrvRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.name);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct TurtlesSrvRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::turtle_controller::TurtlesSrvRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::turtle_controller::TurtlesSrvRequest_<ContainerAllocator>& v)
  {
    s << indent << "name: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.name);
  }
};

} // namespace message_operations
} // namespace ros

#endif // TURTLE_CONTROLLER_MESSAGE_TURTLESSRVREQUEST_H
