// Generated by gencpp from file turtle_controller/TurtlesSrvResponse.msg
// DO NOT EDIT!


#ifndef TURTLE_CONTROLLER_MESSAGE_TURTLESSRVRESPONSE_H
#define TURTLE_CONTROLLER_MESSAGE_TURTLESSRVRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace turtle_controller
{
template <class ContainerAllocator>
struct TurtlesSrvResponse_
{
  typedef TurtlesSrvResponse_<ContainerAllocator> Type;

  TurtlesSrvResponse_()
    : result()  {
    }
  TurtlesSrvResponse_(const ContainerAllocator& _alloc)
    : result(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _result_type;
  _result_type result;





  typedef boost::shared_ptr< ::turtle_controller::TurtlesSrvResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::turtle_controller::TurtlesSrvResponse_<ContainerAllocator> const> ConstPtr;

}; // struct TurtlesSrvResponse_

typedef ::turtle_controller::TurtlesSrvResponse_<std::allocator<void> > TurtlesSrvResponse;

typedef boost::shared_ptr< ::turtle_controller::TurtlesSrvResponse > TurtlesSrvResponsePtr;
typedef boost::shared_ptr< ::turtle_controller::TurtlesSrvResponse const> TurtlesSrvResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::turtle_controller::TurtlesSrvResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::turtle_controller::TurtlesSrvResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::turtle_controller::TurtlesSrvResponse_<ContainerAllocator1> & lhs, const ::turtle_controller::TurtlesSrvResponse_<ContainerAllocator2> & rhs)
{
  return lhs.result == rhs.result;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::turtle_controller::TurtlesSrvResponse_<ContainerAllocator1> & lhs, const ::turtle_controller::TurtlesSrvResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace turtle_controller

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::turtle_controller::TurtlesSrvResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::turtle_controller::TurtlesSrvResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::turtle_controller::TurtlesSrvResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::turtle_controller::TurtlesSrvResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::turtle_controller::TurtlesSrvResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::turtle_controller::TurtlesSrvResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::turtle_controller::TurtlesSrvResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "c22f2a1ed8654a0b365f1bb3f7ff2c0f";
  }

  static const char* value(const ::turtle_controller::TurtlesSrvResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xc22f2a1ed8654a0bULL;
  static const uint64_t static_value2 = 0x365f1bb3f7ff2c0fULL;
};

template<class ContainerAllocator>
struct DataType< ::turtle_controller::TurtlesSrvResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "turtle_controller/TurtlesSrvResponse";
  }

  static const char* value(const ::turtle_controller::TurtlesSrvResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::turtle_controller::TurtlesSrvResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string result\n"
"\n"
;
  }

  static const char* value(const ::turtle_controller::TurtlesSrvResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::turtle_controller::TurtlesSrvResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.result);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct TurtlesSrvResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::turtle_controller::TurtlesSrvResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::turtle_controller::TurtlesSrvResponse_<ContainerAllocator>& v)
  {
    s << indent << "result: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.result);
  }
};

} // namespace message_operations
} // namespace ros

#endif // TURTLE_CONTROLLER_MESSAGE_TURTLESSRVRESPONSE_H
