set(_CATKIN_CURRENT_PACKAGE "create_turtle")
set(create_turtle_VERSION "0.0.0")
set(create_turtle_MAINTAINER "nuc <nuc@todo.todo>")
set(create_turtle_PACKAGE_FORMAT "2")
set(create_turtle_BUILD_DEPENDS "roscpp" "rospy")
set(create_turtle_BUILD_EXPORT_DEPENDS "roscpp" "rospy")
set(create_turtle_BUILDTOOL_DEPENDS "catkin")
set(create_turtle_BUILDTOOL_EXPORT_DEPENDS )
set(create_turtle_EXEC_DEPENDS "roscpp" "rospy")
set(create_turtle_RUN_DEPENDS "roscpp" "rospy")
set(create_turtle_TEST_DEPENDS )
set(create_turtle_DOC_DEPENDS )
set(create_turtle_URL_WEBSITE "")
set(create_turtle_URL_BUGTRACKER "")
set(create_turtle_URL_REPOSITORY "")
set(create_turtle_DEPRECATED "")